/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest_FFmpegCmd */

#ifndef _Included_Jni_FFmpegCmd
#define _Included_Jni_FFmpegCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest_FFmpegCmd
 * Method:    exec
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Jni_FFmpegCmd_exec
  (JNIEnv *, jclass, jint, jobjectArray);

JNIEXPORT jint JNICALL Java_Jni_FFmpegCmd_exit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

void ffmpeg_progress(float progress);
